services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  # redis_data: